version: 2

nodes:
  - id: src
    kind: source
    plugin: ${oc.env:SS_INPUT_PLUGIN,schnitzel_stream.nodes.dev:StaticSource}
    config:
      source_id: ${oc.env:SS_STREAM_ID,stream01}
      url: ${oc.env:SS_INPUT_URL,}
      path: ${oc.env:SS_INPUT_PATH,}
      camera_index: ${oc.env:SS_INPUT_INDEX,0}
      reconnect: true
      reconnect_backoff_sec: 1.0
      reconnect_backoff_max_sec: 10.0

  - id: out
    kind: sink
    plugin: schnitzel_stream.nodes.dev:PrintSink
    config:
      prefix: ${oc.env:SS_STREAM_ID,stream}
      forward: false

edges:
  - from: src
    to: out

config: {}
